### ISSUE TITLE
plugin crash report

### ISSUE THREAD

**Issue by tommyallieri** [honeycombio/terraform-provider-honeycombio#504]
**Versions**
0.24.0

**Steps to reproduce**
unsure. It used to run fine on `0.24.0` and crashed as I was manually cleaning up resources (boards and triggers). Just crashed three times in a row during the planning phase.

**Additional context**
Stack trace from the terraform-provider-honeycombio_v0.24.0 plugin:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbc49c5]

goroutine 630 [running]:
github.com/honeycombio/terraform-provider-honeycombio/honeycombio.resourceDatasetDefinitionRead({0xf18500, 0xc0001e97a0}, 0x0?, {0xceb500?, 0xc0003ff200})
	github.com/honeycombio/terraform-provider-honeycombio/honeycombio/resource_dataset_definition.go:78 +0x685
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0002540e0, {0xf18458, 0xc000551da0}, 0xd?, {0xceb500, 0xc0003ff200})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:823 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0002540e0, {0xf18458, 0xc000551da0}, 0xc000317520, {0xceb500, 0xc0003ff200})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:1117 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000117d0, {0xf18458?, 0xc000551cb0?}, 0xc0007f2b00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:708 +0x6ca
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0xf18490?, {0xf18458?, 0xc0005519b0?}, 0xc0007f2b00)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001e57c0, {0xf18458?, 0xc000550600?}, 0xc0001e8d90)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:783 +0x309
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd90920?, 0xc0001e57c0}, {0xf18458, 0xc000550600}, 0xc000889f00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000117000, {0xf18458, 0xc000550570}, {0xf1e040, 0xc0001ea480}, 0xc000705200, 0xc0002f3350, 0x14c6c08, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc000117000, {0xf1e040, 0xc0001ea480}, 0xc000705200)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 13
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-honeycombio_v0.24.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by dstrelau** [comment]
Thanks for the report @tommyallieri

I believe this is due to a `honeycombio_dataset_definition` resource being in state but being removed by something other than Terraform. #505 should fix this.

We've got a few other things in flight for the next release, so it might be a day or two before I can get a fix into a released build. If you're able to test a provider build from the main branch on your config, that would be great. Otherwise, you might be able to work around the problem by identifying which resource is causing the panic and re-setting the definition to any valid column via the Honeycomb UI.
